# Generated by Django 5.1.5 on 2025-03-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webpagedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=50)),
                ('web_email', models.EmailField(max_length=254)),
                ('web_phone', models.IntegerField(max_length=10)),
                ('web_message', models.TextField(max_length=250)),
            ],
        ),
    ]
