# Generated by Django 5.1.5 on 2025-03-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimateapp', '0002_androiddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartHomeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('switch', 'Smart Switch'), ('sensor', 'Smart Sensor'), ('module', 'Smart Module'), ('other', 'Other Smart Devices')], max_length=20)),
            ],
        ),
    ]
