# Generated by Django 5.1.5 on 2025-03-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimateapp', '0004_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Name',
        ),
        migrations.AddField(
            model_name='property',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='Unnamed Property', max_length=200),
        ),
    ]
