# Generated by Django 5.1.5 on 2025-03-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimateapp', '0007_area_cardealer_customer_vehicles_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
